version: '3'

services:
    app:
        build:
            context: ./docker/go
            dockerfile: Dockerfile
        volumes:
            - ./app:/go/src/app
        working_dir: /go/src/app
        command: go run main.go bird_handlers.go